const SITE_BASE = location.hostname === 'renolix.github.io' ? '/cosmoplus.github.io' : '';
const root = document.querySelector('#admin-root');
const $ = s => root.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => `${new Intl.NumberFormat('fr-DZ').format(Number(n)||0)} DA`;
const CATEGORIES = [['soins-visage','Soins visage'],['solaires','Protection solaire'],['corps','Corps & hygiène'],['cheveux','Cheveux'],['maquillage','Maquillage'],['parfums','Parfums']];
const categoryName = id => CATEGORIES.find(x=>x[0]===id)?.[1] || 'Beauté';
const base = window.COSMOPLUS_CATALOG || [];
let currentUser=null,role=null,tab='dashboard',products=[],orders=[],staff=[],editor=null,orderId=null,unsubscribe=null;
const initialProduct = p => ({...p,cover:p.cover||p.images?.[0],images:p.images||[p.cover].filter(Boolean)});
function notify(message,bad=false){const n=$('#admin-feedback');if(n){n.textContent=message;n.hidden=false;n.className='feedback'+(bad?' error':'')}}
function brand(){return `<a class="admin-brand" href="${SITE_BASE}/"><span><strong>COSMOPLUS</strong><em>BEAUTÉ</em></span></a>`}
function login(message=''){root.innerHTML=`<div class="login-wrap"><div class="login-card">${brand()}<span class="eyebrow">ESPACE PRIVÉ</span><h1>Administration</h1><p>Connectez-vous avec votre compte de la boutique.</p><form id="login-form"><label class="field">E-mail<input type="email" name="email" autocomplete="username" required></label><label class="field">Mot de passe<input type="password" name="password" autocomplete="current-password" required></label><button class="primary" type="submit">SE CONNECTER</button></form><div id="admin-feedback" class="feedback error" ${message?'':'hidden'}>${esc(message)}</div><p><a href="${SITE_BASE}/">← Retour à la boutique</a></p></div></div>`;$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{await KB.auth.signInWithEmailAndPassword(f.elements.email.value.trim(),f.elements.password.value)}catch(error){notify('Connexion impossible : vérifiez votre e-mail et votre mot de passe.',true);b.disabled=false}})}
function frame(content){root.innerHTML=`<div class="admin-layout"><aside class="admin-sidebar">${brand()}<nav class="admin-nav">${[['dashboard','Vue d’ensemble'],['orders','Commandes'],['products','Produits'],['staff','Équipe']].filter(([id])=>id!=='staff'||role==='admin').map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav><a href="${SITE_BASE}/">Voir la boutique ↗</a><button id="logout" class="ghost">Déconnexion</button></aside><div class="admin-main"><header class="admin-top"><span>COSMOPLUS · ADMINISTRATION</span><span>${esc(currentUser.email)}</span></header><main id="admin-content">${content}</main></div></div>`;root.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;editor=null;orderId=null;render()}));$('#logout').addEventListener('click',()=>KB.auth.signOut());bind()}
function heading(kicker,title,side=''){return `<div class="admin-title"><div><small>${kicker}</small><h1>${title}</h1></div>${side}</div><div id="admin-feedback" class="feedback" hidden></div>`}
function productRow(p){return `<article class="data-row"><img src="${esc(p.cover||p.images?.[0]||'')}" alt=""><div class="grow"><h3>${esc(p.name)}</h3><p>${esc(categoryName(p.category))} · ${money(p.price)} · ${p.active===false?'Masqué':'En ligne'}</p></div>${role==='admin'?`<div class="actions"><button class="ghost" data-edit="${esc(p.id)}">Modifier</button><button class="danger" data-hide="${esc(p.id)}">${p.active===false?'Réactiver':'Masquer'}</button></div>`:''}</article>`}
function dashboard(){const active=products.filter(p=>p.active!==false),newOrders=orders.filter(o=>o.status==='nouvelle');return `${heading('COSMOPLUS','Vue d’ensemble')}<div class="panel-grid"><div class="metric"><span>Produits en ligne</span><strong>${active.length}</strong></div><div class="metric"><span>Nouvelles commandes</span><strong>${newOrders.length}</strong></div><div class="metric"><span>Commandes totales</span><strong>${orders.length}</strong></div></div><section class="card" style="margin-top:20px"><h2>Dernières commandes</h2>${orders.slice(0,5).map(orderRow).join('')||'<p>Aucune commande.</p>'}</section>`}
function productsView(){if(editor)return productForm();return `${heading('CATALOGUE','Produits',role==='admin'?'<button class="primary" id="new-product">+ AJOUTER UN PRODUIT</button>':'')}<div class="toolbar"><input id="product-search" type="search" placeholder="Rechercher un produit…"></div><div class="data-list" id="product-list">${products.map(productRow).join('')}</div>`}
function productForm(){const p=editor==='new'?{}:products.find(x=>x.id===editor)||{};return `${heading('CATALOGUE',editor==='new'?'Ajouter un produit':'Modifier le produit')}<form id="product-form" class="card form-grid"><label class="field">Nom du produit *<input name="name" required value="${esc(p.name)}"></label><label class="field">Prix en DA *<input type="number" name="price" required min="0" step="1" value="${esc(p.price)}"></label><label class="field">Catégorie<select name="category">${CATEGORIES.map(([id,label])=>`<option value="${id}" ${p.category===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="field">Stock (laisser vide si inconnu)<input type="number" name="stock" min="0" step="1" value="${p.stock==null?'':esc(p.stock)}"></label><label class="field full">Description<textarea name="description" rows="4">${esc(p.description)}</textarea></label><label class="field full">URL de la photo principale *<input name="cover" type="url" required value="${esc(p.cover||p.images?.[0])}"></label><label class="field">Visibilité<select name="active"><option value="true" ${p.active!==false?'selected':''}>En ligne</option><option value="false" ${p.active===false?'selected':''}>Masqué</option></select></label><div class="form-actions"><button class="primary" type="submit">ENREGISTRER</button><button class="ghost" type="button" id="cancel-edit">Annuler</button></div></form>`}
const STATUS={nouvelle:'Nouvelle',injoignable:'Injoignable',expediee:'Expédiée',livree:'Livrée',annulee:'Annulée'};
function orderRow(o){return `<article class="data-row"><div class="grow"><h3>${esc(o.customer?.name||'Client')}</h3><p>${esc(o.customer?.phone||'')} · ${esc(o.delivery?.wilaya||'')} · ${money(o.total)}</p></div><span class="status ${esc(o.status)}">${esc(STATUS[o.status]||o.status)}</span><button class="ghost" data-order="${esc(o.id)}">Ouvrir</button></article>`}
function ordersView(){if(orderId)return orderDetail();return `${heading('SUIVI DES ACHATS','Commandes')}<div class="data-list">${orders.map(orderRow).join('')||'<div class="empty">Aucune commande.</div>'}</div>`}
function orderDetail(){const o=orders.find(x=>x.id===orderId);if(!o)return ordersView();return `${heading('COMMANDE',`#${esc(o.id.slice(0,8))}`,'<button class="ghost" id="back-orders">← Toutes les commandes</button>')}<div class="card"><h2>${esc(o.customer?.name||'Client')}</h2><p>${esc(o.customer?.phone||'')}</p><p>${esc(o.delivery?.wilaya||'')} · ${esc(o.delivery?.commune||'')} · ${o.delivery?.method==='bureau'?'Bureau':'À domicile'}</p><p>${esc(o.delivery?.address||o.delivery?.office||'')}</p><div class="data-list">${(o.items||[]).map(i=>`<div class="data-row"><img src="${esc(i.image||'')}" alt=""><div class="grow"><h3>${esc(i.name)}</h3><p>Quantité : ${Number(i.quantity)}</p></div><strong>${money(i.unitPrice*i.quantity)}</strong></div>`).join('')}</div><p>Sous-total : ${money(o.subtotal)} · Livraison : ${money(o.shippingFee)} · <strong>Total : ${money(o.total)}</strong></p><label class="field">Statut<select id="order-status">${Object.entries(STATUS).map(([id,label])=>`<option value="${id}" ${o.status===id?'selected':''}>${label}</option>`).join('')}</select></label>${o.notes?`<p>Note : ${esc(o.notes)}</p>`:''}</div>`}
function staffView(){return `${heading('MON ESPACE','Équipe')}<section class="card"><h2>Créer un accès</h2><p>Connexion e-mail et mot de passe sans validation par e-mail.</p><form id="staff-form" class="form-grid"><label class="field">E-mail *<input name="email" type="email" required></label><label class="field">Mot de passe initial *<input name="password" type="password" minlength="12" required></label><label class="field">Rôle<select name="role"><option value="employee">Employé</option><option value="admin">Administrateur</option></select></label><button class="primary" type="submit">CRÉER LE COMPTE</button></form></section><section class="card" style="margin-top:20px"><h2>Accès existants</h2>${staff.map(s=>`<div class="data-row"><div class="grow"><h3>${esc(s.email)}</h3><p>${s.role==='admin'?'Administrateur':'Employé'}</p></div>${s.id!==currentUser.uid?`<button class="danger" data-revoke="${esc(s.id)}">Retirer l’accès</button>`:''}</div>`).join('')}</section>`}
function render(){if(!currentUser)return login();frame(tab==='products'?productsView():tab==='orders'?ordersView():tab==='staff'&&role==='admin'?staffView():dashboard())}
function bind(){root.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{editor=b.dataset.edit;render()}));root.querySelectorAll('[data-hide]').forEach(b=>b.addEventListener('click',async()=>{const p=products.find(x=>x.id===b.dataset.hide);try{await KB.db.collection('products').doc(p.id).set({active:p.active===false,updatedAt:KB.serverTime()},{merge:true});await loadProducts()}catch(e){notify(e.message,true)}}));$('#new-product')?.addEventListener('click',()=>{editor='new';render()});$('#cancel-edit')?.addEventListener('click',()=>{editor=null;render()});$('#product-search')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase('fr');$('#product-list').innerHTML=products.filter(p=>p.name.toLocaleLowerCase('fr').includes(q)).map(productRow).join('');bind()});$('#product-form')?.addEventListener('submit',saveProduct);root.querySelectorAll('[data-order]').forEach(b=>b.addEventListener('click',()=>{orderId=b.dataset.order;render()}));$('#back-orders')?.addEventListener('click',()=>{orderId=null;render()});$('#order-status')?.addEventListener('change',async e=>{try{await KB.db.collection('orders').doc(orderId).update({status:e.target.value,updatedAt:KB.serverTime()});notify('Statut enregistré.')}catch(err){notify(err.message,true)}});$('#staff-form')?.addEventListener('submit',createStaff);root.querySelectorAll('[data-revoke]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Retirer cet accès ?'))return;try{await KB.db.collection('staff').doc(b.dataset.revoke).delete();await loadStaff()}catch(err){notify(err.message,true)}}))}
async function saveProduct(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type="submit"]');b.disabled=true;try{const id=editor==='new'?KB.db.collection('products').doc().id:editor,old=products.find(p=>p.id===id),v=f.elements;const data={name:v.name.value.trim(),short:v.name.value.trim(),price:Number(v.price.value),category:v.category.value,stock:v.stock.value===''?null:Number(v.stock.value),description:v.description.value.trim(),cover:v.cover.value.trim(),images:[v.cover.value.trim()],active:v.active.value==='true',url:old?.url||`/produit/?id=${encodeURIComponent(id)}`,updatedAt:KB.serverTime()};if(!Number.isFinite(data.price)||data.price<0)throw Error('Prix invalide.');await KB.db.collection('products').doc(id).set(data,{merge:true});editor=null;await loadProducts();notify('Produit enregistré.')}catch(err){notify(err.message,true);b.disabled=false}}
async function createStaff(e){e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type="submit"]');b.disabled=true;let secondary;try{const v=f.elements;secondary=firebase.initializeApp(KB_FIREBASE_CONFIG,'staff-create-'+Date.now());const result=await secondary.auth().createUserWithEmailAndPassword(v.email.value.trim(),v.password.value);await KB.db.collection('staff').doc(result.user.uid).set({email:v.email.value.trim(),role:v.role.value,createdAt:KB.serverTime()});await secondary.auth().signOut();await secondary.delete();secondary=null;f.reset();await loadStaff();notify('Compte créé, sans validation par e-mail.')}catch(err){notify(err.message,true);b.disabled=false;if(secondary){await secondary.auth().signOut().catch(()=>{});await secondary.delete().catch(()=>{})}}}
async function loadProducts(){const docs=await KB.db.collection('products').get();const edits=new Map(docs.docs.map(d=>[d.id,d.data()]));products=base.map(initialProduct).map(p=>({...p,...edits.get(p.id),images:edits.get(p.id)?.images||p.images}));for(const d of docs.docs)if(!products.some(p=>p.id===d.id))products.push({id:d.id,...d.data()});products.sort((a,b)=>a.name.localeCompare(b.name,'fr'));render()}
async function loadStaff(){if(role!=='admin')return;const docs=await KB.db.collection('staff').get();staff=docs.docs.map(d=>({id:d.id,...d.data()}));render()}
function loadOrders(){unsubscribe?.();unsubscribe=KB.db.collection('orders').orderBy('createdAt','desc').limit(200).onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));render()},err=>notify('Commandes indisponibles : '+err.message,true))}
KB.auth.onAuthStateChanged(async user=>{unsubscribe?.();if(!user||user.isAnonymous){currentUser=null;role=null;login();return}root.innerHTML='<div class="boot">Vérification de votre accès…</div>';try{const doc=await KB.db.collection('staff').doc(user.uid).get();if(!doc.exists||!['admin','employee'].includes(doc.data().role)){await KB.auth.signOut();login('Ce compte n’a pas encore accès à l’administration.');return}currentUser=user;role=doc.data().role;await loadProducts();if(role==='admin')await loadStaff();loadOrders()}catch(err){root.innerHTML=`<div class="login-wrap"><div class="login-card">${brand()}<h1>Accès indisponible</h1><p>${esc(err.message)}</p></div></div>`}});
